### ISSUE TITLE
Use ipaddress library to handle IPv4/IPv6 addresses

### ISSUE THREAD

**Issue by gustavosr8** [lnls-dig/nxpprog#4]
Use the library [ipaddress](https://docs.python.org/3/library/ipaddress.html) to handle IP addresses instead of hardcode it, as in 

https://github.com/lnls-dig/nxpprog/blob/0b562b8212eb6cde49de20786fc205d00b0d82cb/nxpprog.py#L1270-L1287

**Comment by augustofg** [comment]
#7 makes this irrelevant.
